"""rename record.quantity

Revision ID: 0aa8f0cc2acd
Revises: 993f301a2615
Create Date: 2025-05-09 17:01:58.004582

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0aa8f0cc2acd"
down_revision: Union[str, None] = "993f301a2615"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record", sa.Column("product_quantity", sa.Integer(), nullable=False)
    )
    op.drop_column("record", "quantity")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record",
        sa.Column(
            "quantity", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("record", "product_quantity")
    # ### end Alembic commands ###
