"""record_type_id_not_null

Revision ID: 1919407e6856
Revises: 9f508f95f76f
Create Date: 2025-05-19 03:31:53.376676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1919407e6856"
down_revision: Union[str, None] = "9f508f95f76f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "category",
        "record_type_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "record", "record_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "tag", "record_type_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tag", "record_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "record", "record_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "category", "record_type_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
