"""recordtag cascade delete record

Revision ID: 1a47b4227512
Revises: 1cb2ddf5f154
Create Date: 2025-05-23 00:59:35.924780

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1a47b4227512"
down_revision: Union[str, None] = "1cb2ddf5f154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "record_tag_record_id_fkey", "record_tag", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "record_tag", "record", ["record_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record_tag", type_="foreignkey")
    op.create_foreign_key(
        "record_tag_record_id_fkey",
        "record_tag",
        "record",
        ["record_id"],
        ["id"],
    )
    # ### end Alembic commands ###
