"""record set null on delete

Revision ID: 261fad42c4a0
Revises: 4e3e5d3deb87
Create Date: 2025-06-09 02:54:22.423694

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "261fad42c4a0"
down_revision: Union[str, None] = "4e3e5d3deb87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("record_unit_id_fkey", "record", type_="foreignkey")
    op.drop_constraint("record_category_id_fkey", "record", type_="foreignkey")
    op.create_foreign_key(
        None,
        "record",
        "category",
        ["category_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        None, "record", "unit", ["unit_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record", type_="foreignkey")
    op.drop_constraint(None, "record", type_="foreignkey")
    op.create_foreign_key(
        "record_category_id_fkey",
        "record",
        "category",
        ["category_id"],
        ["id"],
    )
    op.create_foreign_key(
        "record_unit_id_fkey", "record", "unit", ["unit_id"], ["id"]
    )
    # ### end Alembic commands ###
