"""record_tag nullable fks

Revision ID: 4bea4cc98ad8
Revises: d06b924f3d45
Create Date: 2025-05-12 20:39:20.574206

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bea4cc98ad8"
down_revision: Union[str, None] = "d06b924f3d45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "record", "category_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "record", "unit_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "record", "user_id", existing_type=sa.UUID(), nullable=True
    )
    op.drop_constraint("record_category_id_fkey", "record", type_="foreignkey")
    op.drop_constraint("record_user_id_fkey", "record", type_="foreignkey")
    op.drop_constraint("record_unit_id_fkey", "record", type_="foreignkey")
    op.create_foreign_key(None, "record", "unit", ["unit_id"], ["id"])
    op.create_foreign_key(None, "record", "category", ["category_id"], ["id"])
    op.create_foreign_key(None, "record", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record", type_="foreignkey")
    op.drop_constraint(None, "record", type_="foreignkey")
    op.drop_constraint(None, "record", type_="foreignkey")
    op.create_foreign_key(
        "record_unit_id_fkey",
        "record",
        "unit",
        ["unit_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "record_user_id_fkey",
        "record",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "record_category_id_fkey",
        "record",
        "category",
        ["category_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "record", "user_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "record", "unit_id", existing_type=sa.UUID(), nullable=False
    )
    op.alter_column(
        "record", "category_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
