"""recordtag cascade delete tag

Revision ID: 4e3e5d3deb87
Revises: 1a47b4227512
Create Date: 2025-05-27 01:35:25.021121

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4e3e5d3deb87"
down_revision: Union[str, None] = "1a47b4227512"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "record_tag_tag_id_fkey", "record_tag", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "record_tag", "tag", ["tag_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "record_tag", type_="foreignkey")
    op.create_foreign_key(
        "record_tag_tag_id_fkey", "record_tag", "tag", ["tag_id"], ["id"]
    )
    # ### end Alembic commands ###
