"""init db

Revision ID: a14b50680d72
Revises: 
Create Date: 2024-09-02 13:39:22.253624

"""

from typing import Sequence, Union

from alembic import op
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a14b50680d72"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column(
            "id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_username", "user", ["username"], unique=True)
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.Column("category_color", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_category_name_user",
        "category",
        ["category_name", "user_id"],
        unique=True,
    )
    op.create_table(
        "tag",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tag_name", sa.String(), nullable=False),
        sa.Column("tag_color", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_tag_name_user", "tag", ["tag_name", "user_id"], unique=True
    )
    op.create_table(
        "unit",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("unit_name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_unit_name_user", "unit", ["unit_name", "user_id"], unique=True
    )
    op.create_table(
        "record",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("record_date", sa.Date(), nullable=False),
        sa.Column("product_name", sa.String(), nullable=False),
        sa.Column("unit_quantity", sa.Float(), nullable=False),
        sa.Column("product_quantity", sa.Integer(), nullable=False),
        sa.Column("product_price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("category_id", sa.UUID(), nullable=False),
        sa.Column("unit_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("product_price >= 0", name="check_product_price"),
        sa.CheckConstraint(
            "product_quantity > 0", name="check_product_quantity"
        ),
        sa.CheckConstraint("unit_quantity > 0", name="check_unit_quantity"),
        sa.ForeignKeyConstraint(
            ["category_id"], ["category.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["unit_id"], ["unit.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_product_name", "record", ["product_name"], unique=False
    )
    op.create_index("idx_record_date", "record", ["record_date"], unique=False)
    op.create_table(
        "record_tag",
        sa.Column("record_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["record_id"], ["record.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["tag_id"], ["tag.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("record_id", "tag_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("record_tag")
    op.drop_index("idx_record_date", table_name="record")
    op.drop_index("idx_product_name", table_name="record")
    op.drop_table("record")
    op.drop_index("idx_unit_name_user", table_name="unit")
    op.drop_table("unit")
    op.drop_index("idx_tag_name_user", table_name="tag")
    op.drop_table("tag")
    op.drop_index("idx_category_name_user", table_name="category")
    op.drop_table("category")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_index("idx_username", table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
