"""record_tag.created_at

Revision ID: d06b924f3d45
Revises: 0aa8f0cc2acd
Create Date: 2025-05-12 19:50:52.290775

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d06b924f3d45"
down_revision: Union[str, None] = "0aa8f0cc2acd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "record_tag", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("record_tag", "created_at")
    # ### end Alembic commands ###
