"""record nullable

Revision ID: ecdb80081278
Revises: 4bea4cc98ad8
Create Date: 2025-05-12 20:40:33.261642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecdb80081278"
down_revision: Union[str, None] = "4bea4cc98ad8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "record", "product_quantity", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "record",
        "product_quantity",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
