"""update indexes

Revision ID: ed485967d179
Revises: 1919407e6856
Create Date: 2025-05-20 01:35:18.255437

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ed485967d179"
down_revision: Union[str, None] = "1919407e6856"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_category_name_user", table_name="category")
    op.create_index(
        "idx_category_name_user",
        "category",
        ["name", "user_id", "record_type_id"],
        unique=True,
    )
    op.drop_index("idx_name_user", table_name="tag")
    op.create_index(
        "idx_name_user",
        "tag",
        ["name", "user_id", "record_type_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_name_user", table_name="tag")
    op.create_index("idx_name_user", "tag", ["name", "user_id"], unique=True)
    op.drop_index("idx_category_name_user", table_name="category")
    op.create_index(
        "idx_category_name_user", "category", ["name", "user_id"], unique=True
    )
    # ### end Alembic commands ###
